# Generated by Django 5.0 on 2023-12-12 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('Train_Name', models.CharField(max_length=50)),
                ('Train_Number', models.IntegerField()),
                ('Date', models.DateField()),
                ('From_Station', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Destination', models.CharField(max_length=50)),
                ('Departure_Time', models.CharField(max_length=50)),
                ('Arrival_Time', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('Quotas', models.CharField(max_length=50)),
                ('Seats', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=100)),
                ('To', models.CharField(max_length=100)),
                ('Phonenumber', models.CharField(max_length=15)),
                ('Email', models.EmailField(max_length=100)),
                ('DepartureDate', models.DateField(null=True)),
                ('Noofseats', models.IntegerField()),
                ('Quotas', models.CharField(max_length=100)),
                ('Train_Number', models.IntegerField()),
                ('Train_Name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
